pipelines:
  - name: controlplane

    steps:
      - name: trigger_controlplane_builds
        type: Bash
        execution:
          onStart:
            - echo "kicking off all install builds"
            - add_run_variables will_publish_bi="true"
